# Generated by Django 4.2.20 on 2025-04-10 10:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_transaction_type'),
        ('transactionLog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='old_description',
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='logged_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.transaction'),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='type',
            field=models.CharField(max_length=7),
        ),
    ]
