# Generated by Django 4.2.20 on 2025-04-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionLog', '0002_remove_transactionlog_old_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='category',
            field=models.CharField(default='None'),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction',
            field=models.CharField(default='None'),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='user',
            field=models.CharField(default='None'),
        ),
    ]
