# Generated by Django 4.2.20 on 2025-04-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionLog', '0003_alter_transactionlog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10),
        ),
    ]
