# Generated by Django 4.2.20 on 2025-04-07 12:00

from django.db import migrations
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_customuser_managers_customuser_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', finance.models.CustomSoftDeleteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('objects', finance.models.CustomSoftDeleteManager()),
            ],
        ),
    ]
