# Generated by Django 4.2.20 on 2025-04-09 12:58

from django.db import migrations, models
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_customuser_managers_alter_transaction_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category_id',
            field=models.ForeignKey(default='other', on_delete=models.SET(finance.models.Transaction.get_other_category), related_name='has', to='finance.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=7),
        ),
    ]
