# Generated by Django 4.2.20 on 2025-04-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=7),
        ),
    ]
