# Generated by Django 4.2.20 on 2025-04-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_payment', 'Bank_Payment'), ('card', 'Card')], default='cash', max_length=12),
        ),
    ]
