# Generated by Django 4.2.20 on 2025-04-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_customuser_username_alter_transaction_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_payment', 'Bank_Payment')], default='cash', max_length=12),
        ),
    ]
