# Generated by Django 4.2.20 on 2025-04-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_customuser_options_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_email_activity_user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('bank_payment', 'Bank_Payment'), ('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', False)), fields=('id',), name='unique_id_inactive_users'),
        ),
    ]
