# Generated by Django 4.2.20 on 2025-04-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_remove_customuser_unique_email_activity_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_id_inactive_users',
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', False)), fields=('id',), name='unique_id_for_inactive_users'),
        ),
    ]
