# Generated by Django 4.2.20 on 2025-04-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_remove_customuser_unique_id_inactive_users_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_id_for_inactive_users',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_payment', 'Bank_Payment')], default='cash', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email', 'is_active'), name='unique_email_activity_user'),
        ),
    ]
